# Header
menu:
  ## If your site is put in a subdirectory, set Home as '/child/'
  Home: /
  Archives: archives

social:
  email: omidmr@gmail.com
  twitter:
  weibo:
  github: omid
  googleplus: omidmr
  rss: /atom.xml

# Content
fancybox: true # set to true if you want to use it

duoshuo: #duoshuo_shortname
disqus: omidsh #disqus _shortname
google_analytics: UA-53625-3 #Google Analytics Tracking Code
google_adsense_page_level_ads: #Google Adsense Page Level Ads Code

less:
  paths:
    - source/css
  compress:
    true
